using System.ComponentModel.DataAnnotations;

// This test verifies the behavior of NativeAOT.
// Instead of running dotnet test, you must execute the exe generated by dotnet publish.
// In the GitHub Actions workflow:
// - run: dotnet publish -r linux-x64 tests/ConsoleAppFramework.NativeAotTests/ConsoleAppFramework.NativeAotTests.csproj
// - run: tests/ConsoleAppFramework.NativeAotTests/bin/Release/net10.0/linux-x64/publish/ConsoleAppFramework.NativeAotTests

// not parallel to check exit-code
[assembly: NotInParallel]

namespace ConsoleAppFramework.NativeAotTests;

public class NativeAotTest
{
    ConsoleApp.ConsoleAppBuilder app;

    public NativeAotTest()
    {
        Environment.ExitCode = 0; // reset ExitCode

        this.app = ConsoleApp.Create();

        app.UseFilter<LoggingFilter>();
        app.Add("", Commands.Root);
        app.Add("json", Commands.RecordJson);
        // [Bind] commands for AOT testing
        app.Add("bind-basic", Commands.BindBasic);
        app.Add("bind-args", Commands.BindWithArguments);
        app.Add("bind-inherited", Commands.BindWithInheritance);
    }

    [Test]
    public async Task RunWithFilter()
    {
        // check NativeAot trimming,command requires [DynamicDependency]
        string[] runArgs =
        [
            "input.txt",
            "--count", "3",
            "--quiet"
        ];

        await app.RunAsync(runArgs);
        await Assert.That(Environment.ExitCode).IsEqualTo(0);
    }

    [Test]
    public async Task JsonInvalid()
    {
        string[] runArgs =
        [
            "json",
            "--record",
            "{ \"X\" = 10, \"Y\" = 20 }"
        ];

        await app.RunAsync(runArgs);
        await Assert.That(Environment.ExitCode).IsNotEqualTo(0);
    }

    // ========================================
    // [Bind] AOT Tests
    // ========================================

    [Test]
    public async Task BindBasic_InAOTContext()
    {
        Environment.ExitCode = 0;
        string[] runArgs = ["bind-basic", "--host", "myhost", "--port", "3306", "--database", "testdb"];
        await app.RunAsync(runArgs);
        await Assert.That(Environment.ExitCode).IsEqualTo(0);
    }

    [Test]
    public async Task BindBasic_Defaults_InAOTContext()
    {
        Environment.ExitCode = 0;
        // Use defaults - no arguments
        string[] runArgs = ["bind-basic"];
        await app.RunAsync(runArgs);
        await Assert.That(Environment.ExitCode).IsEqualTo(0);
    }

    [Test]
    public async Task BindWithArguments_InAOTContext()
    {
        Environment.ExitCode = 0;
        string[] runArgs = ["bind-args", "input.txt", "output.txt", "--verbose"];
        await app.RunAsync(runArgs);
        await Assert.That(Environment.ExitCode).IsEqualTo(0);
    }

    [Test]
    public async Task BindWithGlobalOptionsInheritance_InAOTContext()
    {
        Environment.ExitCode = 0;
        string[] runArgs = ["bind-inherited", "--name", "test", "--verbose", "--log-level", "debug"];
        await app.RunAsync(runArgs);
        await Assert.That(Environment.ExitCode).IsEqualTo(0);
    }
}

internal static class Commands
{
    public static async Task<int> Root(
        [Argument] string path,
        [Range(1, 10)] int count = 1,
        bool quiet = false,
        CancellationToken cancellationToken = default)
    {
        await Task.Delay(10, cancellationToken);
        if (!quiet)
        {
            Console.WriteLine($"Processing {path} with count {count}");
        }
        return 0;
    }

    public static void RecordJson(MyRecord record)
    {
        Console.WriteLine($"Record: X={record.X}, Y={record.Y}");
    }

    // [Bind] command handlers for AOT testing
    public static int BindBasic([Bind] DatabaseConfig config)
    {
        Console.WriteLine($"[BindBasic] {config.Host}:{config.Port}/{config.Database}");
        return 0;
    }

    public static int BindWithArguments([Bind] FileProcessingOptions options)
    {
        Console.WriteLine($"[BindWithArguments] {options.InputPath} -> {options.OutputPath}, verbose={options.Verbose}");
        return 0;
    }

    public static int BindWithInheritance([Bind] CommandOptions options)
    {
        Console.WriteLine($"[BindWithInheritance] name={options.Name}, verbose={options.Verbose}, logLevel={options.LogLevel}");
        return 0;
    }
}


internal sealed class LoggingFilter(ConsoleAppFilter next) : ConsoleAppFilter(next)
{
    public override async Task InvokeAsync(ConsoleAppContext context, CancellationToken cancellationToken)
    {
        try
        {
            await Next.InvokeAsync(context, cancellationToken);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Unhandled exception: {ex.Message}");
            throw;
        }
    }
}

public record MyRecord(int X, int Y);

// ========================================
// [Bind] attribute types for AOT testing
// ========================================

public class DatabaseConfig
{
    public string Host { get; set; } = "localhost";
    public int Port { get; set; } = 5432;
    public string Database { get; set; } = "mydb";
}

public class FileProcessingOptions
{
    /// <summary>argument, The input file path</summary>
    public string InputPath { get; set; } = "";

    /// <summary>argument, The output file path</summary>
    public string OutputPath { get; set; } = "";

    public bool Verbose { get; set; } = false;
}

public class AppGlobalOptions
{
    public bool Verbose { get; set; } = false;
    public string LogLevel { get; set; } = "info";
}

public class CommandOptions
{
    public string Name { get; set; } = "default";
    public bool Verbose { get; set; } = false;
    public string LogLevel { get; set; } = "info";
}
